cc_test(
    name = "simulator-test",
    srcs = [
        "ccnode_test.cpp",
        "cctree_test.cpp",
        "heap_test.cpp",
        "simulator_test.cpp",
    ],
    deps = [
        "//simulator",
        "@com_google_googletest//:gtest_main",
    ],
)
